insert into comments (user_id, post_id, date_posted, comment_text) values (41, 284, '4/15/2019', 'Suspendisse potenti.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 468, '6/7/2020', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (1, 464, '10/16/2020', 'Nullam molestie nibh in lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (4, 366, '3/9/2019', 'Morbi non lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 128, '5/21/2019', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (54, 49, '5/9/2019', 'Praesent lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 215, '11/2/2019', 'Vestibulum rutrum rutrum neque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (48, 10, '10/14/2019', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (25, 57, '5/5/2019', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into comments (user_id, post_id, date_posted, comment_text) values (49, 1, '6/21/2020', 'Praesent id massa id nisl venenatis lacinia.');
insert into comments (user_id, post_id, date_posted, comment_text) values (24, 285, '9/21/2020', 'Duis at velit eu est congue elementum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (9, 475, '3/29/2019', 'Integer ac neque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (24, 6, '6/25/2019', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into comments (user_id, post_id, date_posted, comment_text) values (51, 499, '7/29/2019', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (48, 114, '6/29/2019', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (18, 5, '9/25/2019', 'In congue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 121, '3/9/2020', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into comments (user_id, post_id, date_posted, comment_text) values (27, 84, '3/23/2019', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (47, 199, '10/21/2019', 'Nulla tellus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (18, 261, '2/18/2020', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 337, '3/29/2020', 'Nulla ac enim.');
insert into comments (user_id, post_id, date_posted, comment_text) values (42, 224, '1/4/2020', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (45, 290, '6/7/2019', 'Suspendisse ornare consequat lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 40, '11/12/2020', 'Vivamus vestibulum sagittis sapien.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 61, '6/19/2020', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (39, 45, '3/23/2020', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into comments (user_id, post_id, date_posted, comment_text) values (55, 241, '10/16/2019', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 410, '4/19/2020', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 46, '7/16/2019', 'Aliquam non mauris.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 386, '10/12/2019', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (56, 290, '12/29/2019', 'Nunc nisl.');
insert into comments (user_id, post_id, date_posted, comment_text) values (8, 37, '8/6/2020', 'In blandit ultrices enim.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 45, '8/15/2020', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (46, 106, '3/12/2020', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into comments (user_id, post_id, date_posted, comment_text) values (27, 233, '3/5/2020', 'Aenean sit amet justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (53, 310, '1/12/2019', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into comments (user_id, post_id, date_posted, comment_text) values (26, 321, '9/5/2020', 'Donec semper sapien a libero.');
insert into comments (user_id, post_id, date_posted, comment_text) values (4, 325, '9/11/2019', 'Fusce consequat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 358, '7/2/2019', 'Fusce consequat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (43, 154, '5/8/2019', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (54, 95, '5/6/2019', 'Nunc purus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (50, 262, '9/17/2020', 'In sagittis dui vel nisl.');
insert into comments (user_id, post_id, date_posted, comment_text) values (38, 266, '6/20/2019', 'Etiam faucibus cursus urna.');
insert into comments (user_id, post_id, date_posted, comment_text) values (30, 441, '12/9/2019', 'Donec quis orci eget orci vehicula condimentum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 445, '11/25/2019', 'Ut tellus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (39, 188, '10/14/2019', 'Duis mattis egestas metus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (57, 94, '4/13/2020', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (53, 368, '7/8/2019', 'Nullam varius.');
insert into comments (user_id, post_id, date_posted, comment_text) values (45, 306, '1/5/2020', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 219, '1/6/2019', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (30, 350, '4/9/2020', 'Vestibulum rutrum rutrum neque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 185, '3/25/2020', 'Pellentesque viverra pede ac diam.');
insert into comments (user_id, post_id, date_posted, comment_text) values (59, 241, '4/21/2020', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 368, '7/30/2020', 'Etiam vel augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (30, 363, '7/16/2020', 'Morbi porttitor lorem id ligula.');
insert into comments (user_id, post_id, date_posted, comment_text) values (17, 434, '3/31/2019', 'Suspendisse ornare consequat lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (9, 119, '5/9/2020', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (15, 134, '3/24/2019', 'Nam nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (18, 149, '6/8/2020', 'Duis bibendum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 497, '11/7/2019', 'Donec quis orci eget orci vehicula condimentum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 93, '11/17/2019', 'Donec ut mauris eget massa tempor convallis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (51, 307, '8/29/2019', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (18, 162, '10/16/2019', 'Praesent blandit.');
insert into comments (user_id, post_id, date_posted, comment_text) values (50, 242, '3/26/2019', 'Nulla justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (59, 129, '6/15/2020', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into comments (user_id, post_id, date_posted, comment_text) values (24, 485, '8/3/2019', 'Nam dui.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 173, '2/25/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (44, 70, '1/14/2019', 'Duis at velit eu est congue elementum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (24, 381, '11/17/2019', 'Morbi non lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (33, 468, '2/29/2020', 'Morbi ut odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (40, 487, '12/3/2018', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 303, '5/16/2019', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (12, 295, '1/29/2020', 'Nunc rhoncus dui vel sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (43, 264, '1/8/2020', 'Curabitur convallis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (53, 55, '7/31/2019', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into comments (user_id, post_id, date_posted, comment_text) values (46, 75, '1/24/2020', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into comments (user_id, post_id, date_posted, comment_text) values (4, 20, '4/25/2020', 'Integer ac leo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 113, '4/29/2019', 'Ut tellus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (43, 247, '3/29/2020', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 20, '4/6/2019', 'Etiam vel augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (34, 376, '7/5/2020', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (14, 288, '4/24/2020', 'Curabitur gravida nisi at nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (60, 490, '12/6/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (13, 432, '9/25/2020', 'Donec posuere metus vitae ipsum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (30, 166, '1/11/2019', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (20, 23, '6/21/2019', 'Nullam molestie nibh in lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 132, '4/9/2019', 'In sagittis dui vel nisl.');
insert into comments (user_id, post_id, date_posted, comment_text) values (25, 176, '5/29/2019', 'Nulla tempus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (2, 451, '10/26/2020', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 86, '5/4/2019', 'Nullam porttitor lacus at turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (50, 481, '8/11/2019', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into comments (user_id, post_id, date_posted, comment_text) values (9, 90, '11/24/2020', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (33, 29, '10/31/2020', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 321, '8/8/2019', 'Suspendisse ornare consequat lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (27, 252, '8/9/2020', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into comments (user_id, post_id, date_posted, comment_text) values (42, 212, '10/10/2020', 'Proin eu mi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (28, 410, '10/15/2019', 'In quis justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (2, 388, '4/5/2020', 'Proin eu mi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (52, 85, '3/7/2019', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into comments (user_id, post_id, date_posted, comment_text) values (42, 338, '12/28/2019', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (22, 267, '10/10/2020', 'Proin at turpis a pede posuere nonummy.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 244, '7/24/2019', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into comments (user_id, post_id, date_posted, comment_text) values (2, 186, '8/2/2019', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (52, 348, '4/23/2020', 'Maecenas tincidunt lacus at velit.');
insert into comments (user_id, post_id, date_posted, comment_text) values (7, 494, '9/16/2019', 'Suspendisse potenti.');
insert into comments (user_id, post_id, date_posted, comment_text) values (21, 256, '12/4/2018', 'Nulla ac enim.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 261, '12/25/2018', 'Aenean lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (36, 157, '2/9/2019', 'Vivamus tortor.');
insert into comments (user_id, post_id, date_posted, comment_text) values (49, 399, '5/24/2020', 'Suspendisse ornare consequat lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (50, 98, '3/9/2019', 'Cras in purus eu magna vulputate luctus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (23, 195, '2/9/2020', 'Nullam porttitor lacus at turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (60, 220, '7/27/2019', 'Donec dapibus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (20, 32, '6/4/2020', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (38, 363, '9/13/2019', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into comments (user_id, post_id, date_posted, comment_text) values (22, 110, '3/29/2019', 'Vivamus tortor.');
insert into comments (user_id, post_id, date_posted, comment_text) values (15, 491, '8/15/2020', 'Nullam varius.');
insert into comments (user_id, post_id, date_posted, comment_text) values (33, 8, '10/27/2020', 'Curabitur in libero ut massa volutpat convallis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (7, 390, '11/2/2020', 'Aenean sit amet justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (51, 448, '1/4/2019', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into comments (user_id, post_id, date_posted, comment_text) values (16, 357, '8/13/2020', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 218, '6/19/2020', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into comments (user_id, post_id, date_posted, comment_text) values (55, 95, '7/1/2020', 'Nullam porttitor lacus at turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (13, 97, '10/30/2020', 'Pellentesque eget nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (50, 266, '6/9/2020', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (24, 497, '6/7/2019', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 67, '5/3/2020', 'Sed accumsan felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 299, '10/23/2020', 'Morbi ut odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (8, 230, '5/1/2020', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into comments (user_id, post_id, date_posted, comment_text) values (39, 69, '5/7/2019', 'Ut at dolor quis odio consequat varius.');
insert into comments (user_id, post_id, date_posted, comment_text) values (54, 112, '6/17/2019', 'Donec dapibus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (39, 67, '8/18/2020', 'Curabitur at ipsum ac tellus semper interdum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (21, 314, '8/27/2019', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (51, 454, '10/27/2020', 'Sed ante.');
insert into comments (user_id, post_id, date_posted, comment_text) values (57, 418, '7/28/2020', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 382, '6/24/2019', 'Maecenas tincidunt lacus at velit.');
insert into comments (user_id, post_id, date_posted, comment_text) values (18, 476, '6/1/2020', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (40, 435, '6/10/2020', 'Suspendisse potenti.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 477, '1/31/2020', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (20, 189, '10/27/2019', 'Cras pellentesque volutpat dui.');
insert into comments (user_id, post_id, date_posted, comment_text) values (13, 328, '9/1/2020', 'Nunc nisl.');
insert into comments (user_id, post_id, date_posted, comment_text) values (49, 345, '6/3/2019', 'Duis bibendum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (44, 497, '9/22/2019', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (22, 104, '2/5/2020', 'Duis at velit eu est congue elementum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (43, 181, '3/29/2020', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 330, '1/1/2020', 'Vestibulum rutrum rutrum neque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (36, 475, '2/15/2019', 'Quisque porta volutpat erat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 365, '5/2/2019', 'Aliquam erat volutpat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 416, '7/25/2019', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into comments (user_id, post_id, date_posted, comment_text) values (16, 163, '3/1/2020', 'Integer ac leo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (38, 246, '8/27/2020', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into comments (user_id, post_id, date_posted, comment_text) values (9, 323, '9/11/2020', 'Aenean lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (36, 148, '12/19/2018', 'Proin eu mi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 318, '12/17/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into comments (user_id, post_id, date_posted, comment_text) values (59, 428, '1/27/2020', 'Aenean sit amet justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (15, 283, '4/22/2019', 'Nam tristique tortor eu pede.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 370, '10/29/2020', 'Integer non velit.');
insert into comments (user_id, post_id, date_posted, comment_text) values (21, 9, '6/17/2020', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into comments (user_id, post_id, date_posted, comment_text) values (7, 289, '7/10/2020', 'Morbi a ipsum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (45, 436, '1/3/2020', 'Fusce posuere felis sed lacus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (24, 411, '5/9/2020', 'Mauris ullamcorper purus sit amet nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (10, 418, '5/14/2020', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into comments (user_id, post_id, date_posted, comment_text) values (34, 230, '10/31/2020', 'Nam tristique tortor eu pede.');
insert into comments (user_id, post_id, date_posted, comment_text) values (59, 435, '12/3/2019', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 281, '2/14/2020', 'Suspendisse potenti.');
insert into comments (user_id, post_id, date_posted, comment_text) values (38, 109, '10/20/2019', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into comments (user_id, post_id, date_posted, comment_text) values (46, 483, '5/17/2019', 'Proin at turpis a pede posuere nonummy.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 417, '10/27/2019', 'Morbi ut odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (17, 77, '4/19/2019', 'Donec ut dolor.');
insert into comments (user_id, post_id, date_posted, comment_text) values (57, 483, '11/14/2019', 'Nullam varius.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 142, '1/9/2020', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 197, '12/6/2018', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (54, 380, '9/25/2020', 'Pellentesque ultrices mattis odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (36, 491, '10/30/2019', 'In sagittis dui vel nisl.');
insert into comments (user_id, post_id, date_posted, comment_text) values (24, 370, '2/6/2020', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (44, 343, '1/28/2019', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 493, '6/4/2019', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into comments (user_id, post_id, date_posted, comment_text) values (26, 254, '11/4/2019', 'Sed sagittis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (20, 138, '7/31/2020', 'Morbi non lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (45, 103, '7/7/2019', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into comments (user_id, post_id, date_posted, comment_text) values (44, 384, '12/17/2018', 'Vivamus vestibulum sagittis sapien.');
insert into comments (user_id, post_id, date_posted, comment_text) values (52, 236, '6/27/2020', 'Suspendisse accumsan tortor quis turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (24, 124, '5/16/2020', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (4, 125, '8/19/2020', 'Aliquam non mauris.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 155, '3/2/2020', 'Proin risus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (51, 373, '5/9/2019', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (46, 264, '3/22/2020', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (8, 496, '12/11/2019', 'Nulla suscipit ligula in lacus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (30, 218, '3/3/2019', 'Cras pellentesque volutpat dui.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 15, '6/24/2020', 'In quis justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (23, 26, '7/13/2019', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 202, '4/13/2019', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (51, 343, '10/1/2019', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 285, '10/9/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into comments (user_id, post_id, date_posted, comment_text) values (13, 468, '9/11/2019', 'Nulla ac enim.');
insert into comments (user_id, post_id, date_posted, comment_text) values (33, 292, '6/11/2020', 'Duis mattis egestas metus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (12, 75, '1/6/2020', 'Cras pellentesque volutpat dui.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 395, '8/25/2020', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into comments (user_id, post_id, date_posted, comment_text) values (42, 38, '3/11/2020', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 71, '12/8/2019', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into comments (user_id, post_id, date_posted, comment_text) values (54, 315, '2/8/2020', 'Suspendisse potenti.');
insert into comments (user_id, post_id, date_posted, comment_text) values (23, 56, '1/25/2020', 'Curabitur gravida nisi at nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 270, '2/15/2019', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into comments (user_id, post_id, date_posted, comment_text) values (33, 430, '10/31/2019', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (40, 393, '9/1/2020', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 384, '5/16/2020', 'Ut tellus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (50, 415, '4/9/2019', 'Etiam justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 110, '3/24/2019', 'Pellentesque ultrices mattis odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 403, '9/6/2019', 'Duis mattis egestas metus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (54, 99, '8/14/2019', 'Nulla ut erat id mauris vulputate elementum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 113, '3/18/2019', 'Suspendisse ornare consequat lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (24, 34, '10/22/2020', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (12, 281, '8/27/2020', 'Aenean lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (18, 26, '7/6/2019', 'Donec dapibus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 268, '10/4/2019', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 51, '2/4/2020', 'Morbi non lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (20, 459, '3/10/2020', 'Duis ac nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (34, 156, '7/4/2019', 'Nulla ut erat id mauris vulputate elementum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (4, 243, '8/3/2019', 'Mauris sit amet eros.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 20, '6/9/2019', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (49, 218, '11/13/2019', 'Proin eu mi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (30, 407, '6/10/2019', 'Nulla tellus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 419, '7/30/2019', 'Aenean auctor gravida sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 340, '8/17/2020', 'Aliquam non mauris.');
insert into comments (user_id, post_id, date_posted, comment_text) values (50, 418, '9/12/2019', 'Donec dapibus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (54, 158, '1/29/2019', 'Curabitur gravida nisi at nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (22, 459, '12/11/2018', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into comments (user_id, post_id, date_posted, comment_text) values (2, 101, '6/24/2020', 'Vivamus tortor.');
insert into comments (user_id, post_id, date_posted, comment_text) values (16, 391, '9/23/2019', 'Pellentesque ultrices mattis odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 419, '6/23/2019', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into comments (user_id, post_id, date_posted, comment_text) values (55, 75, '11/10/2020', 'Mauris ullamcorper purus sit amet nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (16, 200, '11/28/2020', 'Vivamus vestibulum sagittis sapien.');
insert into comments (user_id, post_id, date_posted, comment_text) values (8, 423, '7/26/2019', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 123, '4/3/2020', 'Etiam faucibus cursus urna.');
insert into comments (user_id, post_id, date_posted, comment_text) values (17, 340, '4/3/2019', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 208, '3/13/2019', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 452, '5/25/2019', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (30, 227, '6/2/2019', 'In blandit ultrices enim.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 268, '4/20/2020', 'Cras in purus eu magna vulputate luctus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (15, 289, '9/10/2020', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (55, 201, '7/13/2019', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into comments (user_id, post_id, date_posted, comment_text) values (47, 364, '3/11/2020', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (7, 217, '8/13/2020', 'Donec ut mauris eget massa tempor convallis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (25, 469, '5/14/2020', 'Duis aliquam convallis nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 205, '5/11/2020', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 99, '5/12/2020', 'Fusce posuere felis sed lacus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (26, 407, '6/1/2020', 'Nulla tellus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (51, 156, '9/12/2020', 'Pellentesque viverra pede ac diam.');
insert into comments (user_id, post_id, date_posted, comment_text) values (47, 276, '7/14/2020', 'Nunc nisl.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 213, '12/24/2018', 'Mauris ullamcorper purus sit amet nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (16, 67, '11/19/2020', 'Morbi porttitor lorem id ligula.');
insert into comments (user_id, post_id, date_posted, comment_text) values (2, 489, '3/8/2020', 'Sed sagittis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (40, 102, '7/10/2019', 'Mauris sit amet eros.');
insert into comments (user_id, post_id, date_posted, comment_text) values (44, 311, '2/17/2019', 'Phasellus id sapien in sapien iaculis congue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (30, 182, '8/14/2019', 'Pellentesque eget nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (25, 442, '4/3/2019', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (17, 319, '9/7/2020', 'Morbi porttitor lorem id ligula.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 6, '1/22/2019', 'Mauris sit amet eros.');
insert into comments (user_id, post_id, date_posted, comment_text) values (23, 107, '11/29/2020', 'Donec dapibus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (12, 163, '7/2/2020', 'Suspendisse potenti.');
insert into comments (user_id, post_id, date_posted, comment_text) values (55, 381, '1/6/2020', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 313, '4/26/2019', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (56, 96, '6/20/2020', 'Donec vitae nisi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (7, 351, '1/25/2019', 'Donec vitae nisi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 25, '11/14/2020', 'Duis bibendum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (40, 478, '6/24/2019', 'Nulla mollis molestie lorem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (2, 312, '7/28/2020', 'Vestibulum sed magna at nunc commodo placerat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 65, '5/4/2019', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into comments (user_id, post_id, date_posted, comment_text) values (26, 64, '12/17/2018', 'Nam tristique tortor eu pede.');
insert into comments (user_id, post_id, date_posted, comment_text) values (46, 438, '1/11/2020', 'Integer non velit.');
insert into comments (user_id, post_id, date_posted, comment_text) values (38, 182, '4/14/2020', 'Suspendisse ornare consequat lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (49, 66, '6/19/2020', 'Pellentesque at nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 288, '7/16/2019', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 70, '4/19/2020', 'Etiam pretium iaculis justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 120, '6/30/2019', 'Nam nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (57, 405, '9/8/2019', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into comments (user_id, post_id, date_posted, comment_text) values (57, 20, '8/13/2020', 'Cras pellentesque volutpat dui.');
insert into comments (user_id, post_id, date_posted, comment_text) values (53, 360, '8/17/2019', 'Proin at turpis a pede posuere nonummy.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 373, '10/31/2020', 'Pellentesque viverra pede ac diam.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 452, '7/12/2020', 'Suspendisse potenti.');
insert into comments (user_id, post_id, date_posted, comment_text) values (55, 112, '6/2/2020', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (14, 412, '5/26/2020', 'Suspendisse potenti.');
insert into comments (user_id, post_id, date_posted, comment_text) values (51, 386, '6/26/2020', 'Etiam faucibus cursus urna.');
insert into comments (user_id, post_id, date_posted, comment_text) values (57, 2, '6/9/2020', 'Phasellus in felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (28, 122, '7/26/2019', 'Nunc rhoncus dui vel sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (38, 205, '10/12/2020', 'Cras in purus eu magna vulputate luctus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (1, 136, '1/18/2020', 'Vestibulum rutrum rutrum neque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (59, 51, '2/12/2019', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (50, 171, '4/30/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (2, 474, '3/13/2019', 'Morbi non lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (9, 177, '5/5/2020', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (23, 8, '6/6/2019', 'Phasellus id sapien in sapien iaculis congue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (50, 137, '8/24/2020', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (50, 244, '9/4/2020', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 34, '1/26/2019', 'Morbi a ipsum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (42, 137, '8/15/2019', 'Aliquam erat volutpat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 270, '9/27/2020', 'Maecenas pulvinar lobortis est.');
insert into comments (user_id, post_id, date_posted, comment_text) values (54, 170, '1/21/2020', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 287, '11/24/2019', 'Praesent lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (57, 23, '1/3/2019', 'Nunc purus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (14, 224, '7/24/2020', 'Aliquam erat volutpat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (22, 17, '12/11/2018', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (27, 341, '10/13/2020', 'Aenean auctor gravida sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (34, 257, '3/3/2019', 'Integer ac leo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 314, '3/7/2020', 'Duis at velit eu est congue elementum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 306, '8/13/2020', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into comments (user_id, post_id, date_posted, comment_text) values (28, 182, '7/23/2020', 'Duis aliquam convallis nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 383, '6/19/2019', 'Duis bibendum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (34, 192, '6/21/2020', 'Etiam pretium iaculis justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (43, 342, '10/11/2019', 'Curabitur in libero ut massa volutpat convallis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (7, 230, '10/13/2019', 'Aliquam erat volutpat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (55, 247, '7/3/2020', 'Donec posuere metus vitae ipsum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (25, 252, '11/27/2019', 'Cras pellentesque volutpat dui.');
insert into comments (user_id, post_id, date_posted, comment_text) values (4, 396, '5/1/2020', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 292, '12/31/2018', 'Etiam justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (13, 402, '3/11/2019', 'Cras in purus eu magna vulputate luctus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (26, 414, '3/20/2020', 'Nam dui.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 485, '12/30/2018', 'Nullam varius.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 499, '9/30/2019', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 86, '2/2/2020', 'Integer ac neque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (1, 135, '9/5/2020', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (34, 300, '9/22/2020', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into comments (user_id, post_id, date_posted, comment_text) values (52, 362, '8/5/2019', 'Suspendisse ornare consequat lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 184, '2/17/2019', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (34, 69, '8/19/2020', 'Nam tristique tortor eu pede.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 289, '11/2/2019', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (53, 347, '5/28/2019', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 45, '11/13/2019', 'Donec quis orci eget orci vehicula condimentum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 374, '8/14/2020', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (30, 9, '6/6/2019', 'Duis bibendum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (22, 208, '9/14/2019', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (40, 224, '8/10/2020', 'Donec vitae nisi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (23, 353, '8/12/2019', 'Cras non velit nec nisi vulputate nonummy.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 370, '2/16/2019', 'Nunc purus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (47, 76, '9/19/2019', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (23, 279, '12/28/2018', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (49, 274, '1/5/2019', 'Pellentesque eget nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (49, 213, '8/4/2020', 'Sed sagittis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (53, 325, '7/22/2020', 'Phasellus sit amet erat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (38, 390, '12/24/2018', 'Morbi non quam nec dui luctus rutrum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 199, '3/15/2020', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into comments (user_id, post_id, date_posted, comment_text) values (39, 228, '2/15/2020', 'Suspendisse potenti.');
insert into comments (user_id, post_id, date_posted, comment_text) values (9, 119, '9/20/2020', 'Cras pellentesque volutpat dui.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 177, '6/3/2020', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into comments (user_id, post_id, date_posted, comment_text) values (56, 283, '3/28/2020', 'Pellentesque at nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 107, '4/10/2020', 'Integer a nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (36, 479, '9/2/2019', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (21, 238, '5/22/2019', 'Mauris lacinia sapien quis libero.');
insert into comments (user_id, post_id, date_posted, comment_text) values (44, 160, '12/5/2019', 'Integer a nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 145, '9/10/2019', 'Nulla justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 260, '6/22/2020', 'Integer ac neque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (59, 290, '3/31/2019', 'Mauris sit amet eros.');
insert into comments (user_id, post_id, date_posted, comment_text) values (14, 236, '12/4/2019', 'Cras in purus eu magna vulputate luctus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (40, 279, '4/3/2019', 'Donec vitae nisi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 78, '10/2/2019', 'Mauris lacinia sapien quis libero.');
insert into comments (user_id, post_id, date_posted, comment_text) values (2, 277, '3/19/2019', 'Nulla tellus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (33, 491, '10/13/2019', 'Aliquam non mauris.');
insert into comments (user_id, post_id, date_posted, comment_text) values (14, 76, '12/5/2019', 'Suspendisse potenti.');
insert into comments (user_id, post_id, date_posted, comment_text) values (48, 369, '1/10/2019', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (9, 320, '7/6/2019', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (1, 256, '1/10/2019', 'Aenean fermentum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 305, '4/5/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (17, 424, '9/30/2019', 'Nulla ut erat id mauris vulputate elementum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (25, 41, '7/31/2019', 'Donec dapibus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (60, 83, '5/13/2019', 'Praesent blandit lacinia erat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 297, '1/21/2020', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into comments (user_id, post_id, date_posted, comment_text) values (30, 455, '8/4/2020', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (8, 301, '10/16/2020', 'Praesent id massa id nisl venenatis lacinia.');
insert into comments (user_id, post_id, date_posted, comment_text) values (48, 292, '1/30/2019', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into comments (user_id, post_id, date_posted, comment_text) values (1, 316, '6/2/2019', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 306, '10/7/2019', 'Pellentesque viverra pede ac diam.');
insert into comments (user_id, post_id, date_posted, comment_text) values (18, 41, '8/17/2019', 'Ut at dolor quis odio consequat varius.');
insert into comments (user_id, post_id, date_posted, comment_text) values (10, 92, '10/11/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into comments (user_id, post_id, date_posted, comment_text) values (56, 289, '7/1/2019', 'Suspendisse ornare consequat lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 297, '12/21/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into comments (user_id, post_id, date_posted, comment_text) values (35, 362, '5/27/2019', 'Duis bibendum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (40, 269, '9/12/2019', 'Ut at dolor quis odio consequat varius.');
insert into comments (user_id, post_id, date_posted, comment_text) values (26, 111, '3/19/2020', 'Curabitur at ipsum ac tellus semper interdum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (18, 300, '10/4/2019', 'Duis aliquam convallis nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 204, '12/23/2018', 'Donec vitae nisi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 500, '8/21/2019', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (42, 22, '1/20/2020', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (46, 490, '7/2/2020', 'Praesent blandit lacinia erat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 192, '3/9/2020', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (17, 226, '12/19/2019', 'In eleifend quam a odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (6, 170, '11/5/2019', 'Maecenas pulvinar lobortis est.');
insert into comments (user_id, post_id, date_posted, comment_text) values (41, 407, '12/10/2019', 'Donec ut dolor.');
insert into comments (user_id, post_id, date_posted, comment_text) values (21, 283, '6/4/2020', 'Nulla ac enim.');
insert into comments (user_id, post_id, date_posted, comment_text) values (22, 317, '2/17/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into comments (user_id, post_id, date_posted, comment_text) values (60, 493, '9/15/2019', 'Phasellus in felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (38, 111, '6/22/2019', 'Praesent lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (32, 180, '7/8/2020', 'Nunc rhoncus dui vel sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 357, '10/19/2020', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 359, '11/4/2019', 'Vestibulum rutrum rutrum neque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (17, 66, '12/25/2018', 'Duis aliquam convallis nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (48, 99, '2/8/2019', 'Mauris ullamcorper purus sit amet nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (14, 415, '11/21/2019', 'Morbi a ipsum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (60, 417, '10/20/2019', 'Duis bibendum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 322, '8/21/2020', 'Morbi non lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (16, 33, '3/8/2019', 'Integer a nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (51, 336, '5/31/2020', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 72, '4/13/2019', 'Cras in purus eu magna vulputate luctus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (36, 196, '3/30/2020', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into comments (user_id, post_id, date_posted, comment_text) values (1, 16, '11/1/2020', 'Praesent id massa id nisl venenatis lacinia.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 474, '6/26/2020', 'Praesent id massa id nisl venenatis lacinia.');
insert into comments (user_id, post_id, date_posted, comment_text) values (55, 96, '2/16/2019', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (47, 312, '2/28/2019', 'Aenean sit amet justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (28, 176, '4/18/2019', 'Morbi non quam nec dui luctus rutrum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (8, 138, '7/8/2020', 'Nullam varius.');
insert into comments (user_id, post_id, date_posted, comment_text) values (5, 247, '7/2/2019', 'Etiam faucibus cursus urna.');
insert into comments (user_id, post_id, date_posted, comment_text) values (48, 12, '10/16/2019', 'Nam nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (60, 163, '4/14/2020', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into comments (user_id, post_id, date_posted, comment_text) values (19, 469, '9/1/2019', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (43, 228, '3/21/2020', 'Donec ut dolor.');
insert into comments (user_id, post_id, date_posted, comment_text) values (40, 63, '6/8/2020', 'Nulla facilisi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (37, 346, '11/22/2019', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into comments (user_id, post_id, date_posted, comment_text) values (16, 351, '5/7/2019', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (9, 176, '10/24/2019', 'Ut tellus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (21, 490, '10/1/2020', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (7, 105, '8/4/2020', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into comments (user_id, post_id, date_posted, comment_text) values (57, 259, '5/27/2020', 'Duis aliquam convallis nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (57, 466, '9/26/2019', 'Nulla ac enim.');
insert into comments (user_id, post_id, date_posted, comment_text) values (36, 454, '1/1/2019', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (59, 205, '10/10/2020', 'Proin at turpis a pede posuere nonummy.');
insert into comments (user_id, post_id, date_posted, comment_text) values (22, 436, '2/28/2019', 'Sed accumsan felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (12, 199, '5/19/2020', 'Donec posuere metus vitae ipsum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (54, 210, '11/26/2020', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into comments (user_id, post_id, date_posted, comment_text) values (16, 290, '1/14/2019', 'Aenean sit amet justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (17, 74, '4/25/2020', 'Suspendisse ornare consequat lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (12, 386, '1/12/2020', 'Praesent blandit.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 422, '5/25/2020', 'Etiam faucibus cursus urna.');
insert into comments (user_id, post_id, date_posted, comment_text) values (46, 321, '9/29/2019', 'In hac habitasse platea dictumst.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 218, '9/20/2020', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (21, 224, '9/3/2019', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into comments (user_id, post_id, date_posted, comment_text) values (15, 484, '8/4/2020', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into comments (user_id, post_id, date_posted, comment_text) values (27, 442, '2/2/2019', 'Curabitur gravida nisi at nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (14, 479, '3/25/2020', 'Vivamus tortor.');
insert into comments (user_id, post_id, date_posted, comment_text) values (39, 221, '10/27/2020', 'Aliquam non mauris.');
insert into comments (user_id, post_id, date_posted, comment_text) values (34, 260, '12/30/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into comments (user_id, post_id, date_posted, comment_text) values (16, 15, '4/24/2019', 'Nunc purus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (16, 80, '11/6/2020', 'Maecenas pulvinar lobortis est.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 43, '6/13/2019', 'Praesent lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (48, 81, '12/1/2019', 'Duis bibendum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (17, 415, '5/27/2019', 'Maecenas tincidunt lacus at velit.');
insert into comments (user_id, post_id, date_posted, comment_text) values (53, 170, '11/14/2019', 'Curabitur gravida nisi at nibh.');
insert into comments (user_id, post_id, date_posted, comment_text) values (27, 422, '6/1/2020', 'Suspendisse ornare consequat lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (1, 150, '10/7/2019', 'Cras non velit nec nisi vulputate nonummy.');
insert into comments (user_id, post_id, date_posted, comment_text) values (9, 468, '8/15/2019', 'Vivamus tortor.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 498, '8/27/2019', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (59, 97, '1/21/2020', 'Ut at dolor quis odio consequat varius.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 63, '8/21/2020', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into comments (user_id, post_id, date_posted, comment_text) values (57, 271, '4/12/2019', 'Morbi ut odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (34, 39, '1/7/2020', 'Phasellus id sapien in sapien iaculis congue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (44, 3, '6/9/2020', 'Duis mattis egestas metus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (10, 329, '12/26/2018', 'Aliquam non mauris.');
insert into comments (user_id, post_id, date_posted, comment_text) values (43, 306, '9/1/2019', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (42, 203, '6/12/2019', 'Suspendisse accumsan tortor quis turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (4, 14, '7/11/2020', 'Pellentesque at nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (13, 252, '2/13/2020', 'Suspendisse accumsan tortor quis turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (47, 4, '11/29/2019', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (41, 459, '1/7/2020', 'Aliquam erat volutpat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (10, 403, '5/8/2020', 'Suspendisse accumsan tortor quis turpis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (8, 284, '2/7/2020', 'Etiam vel augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (8, 172, '5/30/2020', 'In congue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (43, 495, '4/3/2020', 'Aenean fermentum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (56, 175, '1/28/2020', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (52, 280, '4/18/2020', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into comments (user_id, post_id, date_posted, comment_text) values (1, 31, '5/28/2019', 'Nunc rhoncus dui vel sem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (25, 186, '12/17/2019', 'Proin at turpis a pede posuere nonummy.');
insert into comments (user_id, post_id, date_posted, comment_text) values (15, 431, '1/20/2020', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (29, 130, '8/25/2019', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (31, 446, '6/23/2020', 'Ut at dolor quis odio consequat varius.');
insert into comments (user_id, post_id, date_posted, comment_text) values (32, 320, '2/2/2019', 'Nulla suscipit ligula in lacus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 106, '6/18/2019', 'Nulla nisl.');
insert into comments (user_id, post_id, date_posted, comment_text) values (42, 177, '1/2/2019', 'Donec semper sapien a libero.');
insert into comments (user_id, post_id, date_posted, comment_text) values (3, 414, '1/13/2019', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into comments (user_id, post_id, date_posted, comment_text) values (42, 316, '7/10/2020', 'Nulla ac enim.');
insert into comments (user_id, post_id, date_posted, comment_text) values (15, 85, '10/7/2020', 'Aenean fermentum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (20, 470, '12/29/2018', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (23, 398, '10/6/2020', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into comments (user_id, post_id, date_posted, comment_text) values (22, 24, '12/2/2018', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (33, 421, '8/29/2019', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into comments (user_id, post_id, date_posted, comment_text) values (22, 152, '10/20/2019', 'Proin at turpis a pede posuere nonummy.');
insert into comments (user_id, post_id, date_posted, comment_text) values (2, 195, '5/26/2019', 'Morbi ut odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (10, 271, '3/16/2019', 'Pellentesque eget nunc.');
insert into comments (user_id, post_id, date_posted, comment_text) values (48, 155, '4/28/2020', 'Nulla justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (56, 324, '10/31/2020', 'Vestibulum sed magna at nunc commodo placerat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (11, 231, '1/22/2019', 'Integer ac neque.');
insert into comments (user_id, post_id, date_posted, comment_text) values (13, 24, '9/29/2020', 'Vestibulum sed magna at nunc commodo placerat.');
insert into comments (user_id, post_id, date_posted, comment_text) values (21, 397, '2/26/2019', 'Ut tellus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (36, 214, '7/10/2019', 'Etiam pretium iaculis justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (23, 267, '3/15/2020', 'Duis at velit eu est congue elementum.');
insert into comments (user_id, post_id, date_posted, comment_text) values (24, 454, '8/20/2019', 'Aenean sit amet justo.');
insert into comments (user_id, post_id, date_posted, comment_text) values (38, 467, '10/8/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into comments (user_id, post_id, date_posted, comment_text) values (13, 94, '7/31/2020', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (33, 463, '10/9/2019', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into comments (user_id, post_id, date_posted, comment_text) values (52, 466, '2/13/2019', 'Donec ut mauris eget massa tempor convallis.');
insert into comments (user_id, post_id, date_posted, comment_text) values (58, 53, '11/10/2020', 'Nulla tempus.');
insert into comments (user_id, post_id, date_posted, comment_text) values (36, 425, '11/23/2019', 'Praesent blandit.');
insert into comments (user_id, post_id, date_posted, comment_text) values (56, 418, '10/30/2019', 'Etiam vel augue.');
insert into comments (user_id, post_id, date_posted, comment_text) values (33, 50, '5/20/2019', 'In hac habitasse platea dictumst.');
