INSERT INTO tags (post_id, name)
VALUES (1, 'plants'),
(1, 'plant'),
(1, 'nature'),
(2, 'cat'),
(2, 'pet'),
(3, 'recipe'),
(3, 'soup'),
(3, 'chinese'),
(4, 'sweater'),
(4, 'crochet'),
(4, 'yarn'),
(4, 'pattern'),
(4, 'chunky sweater'),
(4, 'tutorial'),
(5, 'furniture'),
(5, 'home'),
(5, 'design'),
(5, 'home making'),
(5, 'lifestyle'),
(6, 'github'),
(6, 'README'),
(6, 'profile'),
(6, 'markdown'),
(7, 'mechanical keyboards'),
(7, 'keyboard'),
(7, 'shop'),
(7, 'shopping'),
(7, 'typing'),
(8, 'animation'),
(8, 'art'),
(8, 'movie'),
(8, 'Matthias Lechner'),
(8, 'concept'),
(8, 'art'),
(8, 'disney'),
(9, 't-shirt'),
(9, 'shirt'),
(9, 'clothes'),
(9, 'shopping'),
(9, 'seal'),
(9, 'animals'),
(9, 'seals'),
(10, 'free'),
(10, 'brushes'),
(10, 'procreate'),
(10, 'digital'),
(10, 'drawing'),
(10, 'MattyB'),
(10, 'bundle'),
(10, 'INKDUP'),
(10, 'natural'),
(10, 'ink'),
(11, 'pattern'),
(11, 'maker'),
(11, 'background'),
(11, 'free'),
(11, 'generator'),
(11, 'pattern cooler'),
(11, 'patterncooler'),
(12, 'flexbox'),
(12, 'css'),
(12, 'tutorial'),
(12, 'guide'),
(12, 'website'),
(12, 'html'),
(12, 'design'),
(13, 'Insecta'),
(13, 'shoes'),
(13, 'shopping'),
(13, 'style'),
(13, 'fashion'),
(13, 'shop'),
(13, 'bug'),
(13, 'insect'),
(14, 'pokemon'),
(14, 'youtube'),
(14, 'video'),
(14, 'pokerez'),
(15, 'photography'),
(15, 'camera'),
(15, 'lightroom'),
(15, 'peter mckinnon'),
(15, 'shop');
